---

language: python
python: "2.7"

branches:
  only:
    - develop
    - master

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.1
  # Install Test Kitchen
  - gem install test-kitchen
  - gem install kitchen-ansible
  - gem install kitchen-docker


script:
#  # Install Role Dependencies
#  - make test_deps
  # Check the role/playbook's syntax.
#  - ansible-playbook --syntax-check --list-tasks -i tests/integration/default/inventory tests/integration/default/default.yml
  - kitchen converge all
